#!/bin/bash
cd ~/
ln -s dotfiles/dotvim
ln -s dotfiles/dottmux

# dotvim links setup
~/dotvim/createlinks

# dotconfig links setup
~/dotfiles/dotconfig/createlinks

# dottmux links setup
~/dotfiles/dottmux/createlinks
